In [37]:
from tensorflow.keras.preprocessing.text import one_hot

In [38]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [39]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [40]:
## Define the vocabulary size
voc_size=10000

In [41]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[3282, 7299, 2800, 5707],
 [3282, 7299, 2800, 2338],
 [3282, 1731, 2800, 795],
 [3055, 8411, 3943, 4236, 7972],
 [3055, 8411, 3943, 4236, 691],
 [3582, 3282, 7200, 2800, 2142],
 [7962, 108, 2783, 4236]]

In [42]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [43]:
import numpy as np

In [44]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3282 7299 2800 5707]
 [   0    0    0    0 3282 7299 2800 2338]
 [   0    0    0    0 3282 1731 2800  795]
 [   0    0    0 3055 8411 3943 4236 7972]
 [   0    0    0 3055 8411 3943 4236  691]
 [   0    0    0 3582 3282 7200 2800 2142]
 [   0    0    0    0 7962  108 2783 4236]]


In [45]:
## feature representation
dim=10

In [50]:
model=Sequential()
model.add(Embedding(input_dim=voc_size,output_dim=dim,input_length=sent_length))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [52]:
# Force build with dummy input
dummy_input = np.zeros((1, sent_length), dtype=int)
model(dummy_input)  # Call the model to build it

# Now it will show proper parameters
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ (1, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [53]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ (1, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [54]:
model.predict(embedded_docs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step


array([[[-0.03922682, -0.01065439, -0.03662262,  0.02610015,
          0.00553023,  0.03906376, -0.03785887,  0.01036619,
         -0.01841078, -0.02994597],
        [-0.03922682, -0.01065439, -0.03662262,  0.02610015,
          0.00553023,  0.03906376, -0.03785887,  0.01036619,
         -0.01841078, -0.02994597],
        [-0.03922682, -0.01065439, -0.03662262,  0.02610015,
          0.00553023,  0.03906376, -0.03785887,  0.01036619,
         -0.01841078, -0.02994597],
        [-0.03922682, -0.01065439, -0.03662262,  0.02610015,
          0.00553023,  0.03906376, -0.03785887,  0.01036619,
         -0.01841078, -0.02994597],
        [ 0.00068134, -0.01974344, -0.02082532, -0.03066472,
          0.02549632, -0.04159302,  0.00910385, -0.0438115 ,
         -0.01737249,  0.04481299],
        [-0.04828629, -0.003413  ,  0.01839251,  0.0202123 ,
         -0.0191204 ,  0.01168252,  0.02857781, -0.01764685,
          0.00496546,  0.02200845],
        [-0.0075609 , -0.02039441,  0.04527917, -0.0

In [55]:
embedded_docs[0]

array([   0,    0,    0,    0, 3282, 7299, 2800, 5707], dtype=int32)

In [57]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step


array([[[-0.03922682, -0.01065439, -0.03662262,  0.02610015,
          0.00553023,  0.03906376, -0.03785887,  0.01036619,
         -0.01841078, -0.02994597],
        [-0.03922682, -0.01065439, -0.03662262,  0.02610015,
          0.00553023,  0.03906376, -0.03785887,  0.01036619,
         -0.01841078, -0.02994597],
        [-0.03922682, -0.01065439, -0.03662262,  0.02610015,
          0.00553023,  0.03906376, -0.03785887,  0.01036619,
         -0.01841078, -0.02994597],
        [-0.03922682, -0.01065439, -0.03662262,  0.02610015,
          0.00553023,  0.03906376, -0.03785887,  0.01036619,
         -0.01841078, -0.02994597],
        [ 0.00068134, -0.01974344, -0.02082532, -0.03066472,
          0.02549632, -0.04159302,  0.00910385, -0.0438115 ,
         -0.01737249,  0.04481299],
        [-0.04828629, -0.003413  ,  0.01839251,  0.0202123 ,
         -0.0191204 ,  0.01168252,  0.02857781, -0.01764685,
          0.00496546,  0.02200845],
        [-0.0075609 , -0.02039441,  0.04527917, -0.0